version: '3'
services:
  mongodb:
    image: mongo:4.4.6
    container_name: wbrick-demo-mongodb
    volumes:
      - ./data/db:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: dbroot
      MONGO_INITDB_ROOT_PASSWORD: Gri42Mvyk3j2PXIiTdn6CCA8JDSST7yv
    logging:
      driver: json-file
      options:
        max-size: 50m
        max-file: '2'
    restart: always
    ports:
      - "17021:27017"

  mongo_express:
    image: mongo-express:latest
    container_name: wbrick-demo-mongodb-express
    depends_on:
      - mongodb
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb:27017
      - ME_CONFIG_MONGODB_ADMINUSERNAME=dbroot
      - ME_CONFIG_MONGODB_ADMINPASSWORD=Gri42Mvyk3j2PXIiTdn6CCA8JDSST7yv
      - ME_CONFIG_BASICAUTH_USERNAME=dbroot
      - ME_CONFIG_BASICAUTH_PASSWORD=Gri42Mvyk3j2PXIiTdn6CCA8JDSST7yv
    ports:
      - "17022:8081"
    restart: always

  redis:
    image: redis
    command: redis-server --requirepass lfluYk4reffZDjzzXfeNA2ub9odfJ1Ic
    container_name: wbrick-demo-redis
    restart: always
    ports:
      - "17023:6379"
    logging:
      driver: json-file
      options:
        max-size: 100m
        max-file: '2'